bakkeby/st-flexipatch

- x.c
Hi,
I was having an issue where the alpha would reset, i.e. the terminal would go opaque, when setting the background color from an escape sequence:
```sh
printf "\033]4;258;#000000\033\\"
```
I copy pasted the alpha stuff of the `xloadcols` function into the `xsetcolorname` function and it fixed my issue.
> Add alpha to background color from escape sequence

- config.def.h
Hi,
The `RELATIVEBORDER_PATCH` isn't compatible with the `XRESOURCES_PATCH`, `borderpx` is undefined when `RELATIVEBORDER_PATCH` is active and should be replaced with `borderperc`.
> XRESOURCES_PATCH with RELATIVEBORDER_PATCH

- patch/xresources.c
- patch/xresources.h
- patches.def.h
- x.c
Hi again,
For my setup, I want to change the color scheme on the fly, hence my previous escape sequence PR #15, I couldn't find a clean solution with escape sequences so I added a patch to get `st` to reload the Xresources to update the colorscheme, when it receives a `SIGUSR1` signal.
As far as I can tell it doesn't break anything, but please don't take my word for it 😀
Feel free to close this PR if you don't think this is useful.
> Add XRESOURCES_RELOAD_PATCH

- patch/openurlonclick.c
Fixes some overflows that could crash st if the incoming url was too long
> Fix buffer overflows in openurlonclick.c

- sixel.c
Tested with and without alpha patch applied. Simply setting alpha to 255 seems to fix it. I didn't set `dst` on lines 263 and 273 because those loops are impossible to reach.
Closes #13
> Fix white background bleeding through sixel images:

- x.c
I found two bugs in the anysize patch which can leave stripes on the borders when the patch is trying to clear them. So, for example, if you are using theme.sh to change the theme, these issues may occur and for that reason the anysize-nobar is designed to fix them. Unfortunately, that patch isn't attempting to fix the original problem but trying to circumvent it by doing some questionable things. But after this fix, the anysize-nobar patch shouldn't be needed anymore and could be removed unless it's doing something else I'm not aware of.
Here is some detailed info about the bugs:
**The definition of xclear function**
```
xclear(int x1, int y1, int x2, int y2)
```
**The first bug**
```
if (x == 0) {
xclear(0, (y == 0)? 0 : winy, win.vborderpx,
winy + win.ch +
((winy + win.ch >= …
```
> Fix border issues in the anysize patch

- config.def.h
- patch/openurlonclick.c
- patch/openurlonclick.h
- patch/scrollback.c
- patch/st_include.h
- patch/x_include.h
- st.c
- st.h
- x.c
The openurlonclick and scrollback patches are now working together,
so links can be clicked in the scrollback buffer too. This update also
adds url underlining and other improvements to the openurlonclick patch.
The full list of changes in the openurlonclick patch:
- Adds scrollback support
- Adds modkey option
- Better url detection
- Underlines url when the mouse pointer is over a link
- Opens a browser as a background process, so it won't lock the terminal anymore
- Fixes a segmentation fault bug
Please consider taking your time to review this extensive update because even though I tested it with numerous patch combinations, there are still likely edge cases that can cause issues.
Cheers
> Add scrollback support to the openurlonclick patch

- patch/xresources.c
This patch 1) improves reloading X resources - by considering fonts in
a way nearly identical to function `zoomabs`' - and 2) re-renders st so
that changed colors and fonts can be seen.
> XRESOURCES_RELOAD_PATCH reload fonts + re-render

- patch/keyboardselect_st.c
Scrolling back and then entering keyboardselect's copy mode causes
glitched text to appear when moving the cursor. This is because the
keyboardselect patch is not aware of the scrollback history (term.hist),
so it takes the text from the last displayed screen (term.line).
> Fixed a glitch when using the keyboardselect and scrollback patches

- st.c
- x.c
This patch fixes the following sixel issues:
- The current sixel implementation cleared all cells from the left side of the image when the image was drawn. The fix only clears the cells where the image will be drawn.
- The deletion routine didn't work correctly. In certain situations, it left the image or images undrawn. For example, if the first image was marked for deletion, it didn't draw the second one.
- The drawing routine caused a high cpu usage, because XCopyArea() triggered the X server to send the NoExpose event, which caused sixels to be redrawn and the X server to send another NoExpose event and so on. This loop caused constant redraw of sixels and high cpu usage. The fix prevents the X server from sending GraphicsExpose and NoExpose events.
The patch also adds a control …
> Fix sixel issues and add a clearing sequence

- Makefile
When st desktop entry already exists it throws error when running make
> Check for already exisiting desktop entry

- sixel.c
- st.c
- st.h
- x.c
Changes:
- Move sixel_parser_parse() from tputc() to twrite()
- Add missing 8452, DECSDM, XTSMGRAPHICS and XTWINOPS sequences
- Add more conditional blocks for the scrollback and sync patches
- Remove unused reflow_y from ImageList. It is only used for the scrollback-reflow patch in st-sx.
> sixel: move sixel_parser_parse() and add missing sequences and blocks

- x.c
The buffer overflow occurs when the ligatures patch is enabled and xmakeglyphfontspecs() returns more than one XftGlyphFontSpec.
Ref. https://github.com/cog1to/st-ligatures/issues/35
> Fix buffer overflow in xdrawglyph()

- README.md
- config.def.h
- patch/keyboardselect_reflow.txt
- patch/keyboardselect_reflow_st.c
- patch/keyboardselect_reflow_st.h
- patch/keyboardselect_reflow_x.c
- patch/keyboardselect_reflow_x.h
- patch/keyboardselect_x.c
- patch/openurlonclick.c
- patch/reflow.c
- patch/reflow.h
- patch/st_include.c
- patch/st_include.h
- patch/x_include.c
- patch/x_include.h
- patches.def.h
- sixel.c
- st.c
- st.h
- win.h
- x.c
This adds the reflow "patch" based on @veltza's implementation.
Closes #34
> Adding reflow patch

- x.c
Crashing happens when you zoom out and the width or height of an image becomes zero.
> sixel: prevent crashing when size is zero

- x.c
It's annoying to use the search bar when it's behind an image. So this fix prevents that from happening.
> sixel: prevent drawing on search bar

- x.c
This fixes an issue where images on the main screen don't scale when you increase or decrease the font size on the alt screen.
> sixel: scale images on both screens when zooming in/out

- patch/reflow.c
- st.c
- x.c
In the current implementation, when text is written over an image, we have to cut the entire text line out of the image, regardless of how long the text is. It doesn't look good, but it was a design choice for the following reasons:
1) To keep the sixel engine as fast as possible
2) Most applications do not write text on the images anyway
To bring the st terminal in line with other terminals that support sixels, I have now improved the sixel renderer so that the images can now have gaps, which allows the text to be printed inside the images. The changes should not affect performance in normal cases. Only when the renderer has to deal with the text there might be some performance hits depending on how many gaps there are in the images.
> sixel: improve the renderer

- sixel.c
Old images are automatically deleted if a new image is spawned over them. This prevents them from piling up and choking the terminal when viewing animated gifs.
Now if you use the latest version of Chafa to view the gifs, it will set the transparency attribute (P2=1) to all sixel images regardless of whether they are transparent or not. This prevents the auto-delete from working because if the image is transparent, we can't delete any images behind it.
The solution is that since Chafa fills the animation frames with an opaque black background color, we treat the images as non-transparent if they don't have any transparent pixels. This keeps the auto-delete running with the new Chafa.
Although the solution works now, it may not be a long-term solution.
> sixel: prevent images from piling up

- st.c
This fixes the current implementation, which does not delete an image if an application first erases the image and then spawns a new transparent image in its place. The reason it didn't work before was because the two operations were handled at different stages in the rendering pipeline.
> sixel: fix image deletion issue

- config.def.h
I notice that it is not possible to scroll with the mouse wheel while holding down any modifier except Shift, neither when clicking.
So I can't left click, drag and scroll back to select some text to copy.
The latest official patch [st-scrollback-mouse-altscreen-20220127-2c5edf2.diff](https://st.suckless.org/patches/scrollback/st-scrollback-mouse-altscreen-20220127-2c5edf2.diff) uses XK_ANY_MOD instead of XK_NO_MOD that fixes this inconvenience.
> use XK_ANY_MOD with altscreen mouse scrollback patch

- config.def.h
- patch/osc133.c
- patch/osc133.h
- patch/x_include.c
- patch/x_include.h
- patches.def.h
- st.c
- st.h
This patch introduces support for OSC133 as discussed in #126. It borrows veltza's st-sx implementation and introduces two new key bindings, `<ctrl+shift+z/x>` to scroll between prompts.
> osc133: initial patch implementation

- patch/newterm.c
- patch/newterm.h
- patch/osc7.c
- patch/osc7.h
- patch/st_include.c
- patch/st_include.h
- patches.def.h
- st.c
- st.h
This implements OSC7 support for the newterm patch based on @veltza 's implementation.
* https://codeberg.org/dnkl/foot/wiki#spawning-new-terminal-instances-in-the-current-working-directory
* https://github.com/veltza/st-sx/commit/817865c2c6ed905af8849580e58bdcf399216fbd
Closes #153
> osc7: initial patch implementation

- x.c
Some old clipboard managers, such as greenclip and parcellite, constantly poll applications with SelectionRequest events, which breaks the internal timer and blinking cursor. This fix prevents these events from causing any disruption.
Fixes #172
> Prevent SelectionRequests from interfering with blinking cursor

- st.c
Apply fix from st repository, commit [98610fc](https://git.suckless.org/st/commit/98610fcd37f655d44586323dc86c1d013c2798ce.html)
---
The kitty keyboard protocol docs recommend CSI ? u to query support for that protocol, see https://sw.kovidgoyal.net/kitty/keyboard-protocol/
For better or worse, fish shell uses this query to work around bugs in other terminals triggered by requesting that protocol via CSI = 5 u.
Unfortunately, st interprets CSI ? u as DECRC (restore cursor position). reproduce with 'printf "\x1b[?u"; cat'.
fish could work around this by switching to the alternate screen before running this query; but that might cause tearing on terminals that don't support Synchronized Output. I'm not sure.
In the meantime, let's correct our parser.
This adds a redundant else-after-return, …
> Do not interpret CSI ? u as DECRC
